apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: noi-subscription
  namespace: {{ .Values.namespace }}
spec:
  channel: v1.7
  installPlanApproval: Automatic
  name: noi
  source: {{ .Values.catalog_source }}
  sourceNamespace: openshift-marketplace
  startingCSV: noi.v1.4.0